# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
def shared_pods
    pod 'RxSwift', '6.1.0'
    pod 'RxCocoa', '6.1.0'
end


workspace 'Play'

target 'App' do
# Pods for App
shared_pods

end

target 'Common' do
project '../Common/Common'
  shared_pods
end

